config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins, controllers: { sessions: 'admins/sessions' } 
  devise_for :usuarios, controllers: { sessions: 'usuarios/sessions' }
  
  resources :pets do
  resources :appointments
 end
 root to: 'pets#index'

 devise_scope :admin do
	get 'admins/users/list', to: 'admins/sessions#list', as: 'users_list'
end

 get'/citas', to: 'appointments#index', as: 'appointments'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :pet
	validates :fecha, presence: true
	validates :hora, presence: true
	validates :consultorio, presence: true
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @pet = Pet.find(params[:pet_id])
    @appointment = @pet.appointments.create(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:fecha, :hora, :consultorio, :pet_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<%= div_for appointment do %>

	<p id="notice"><%= notice %></p>
<table>
  <thead>
  </thead>
  <tbody>
   
      <tr>
        <td width=25%><%= appointment.fecha %></td>
        <td width=25%><%= appointment.hora %></td>
        <td width=25%><%= appointment.consultorio %></td>
       
        <td width=25%><%= time_ago_in_words(appointment.created_at)%></td>
      </tr>
    
  </tbody>
</table>
<% end %>

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fecha %>
    <%= f.input :hora %>
    <%= f.input :consultorio %>
    <%= f.input :pet_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/appointments/create.js.erb
var new_appointment =$("<%= escape_javascript(render(:partial =>@appointment))%>").hide();
$('#appointments').prepend(new_appointment);
$('#appointment_<%=@appointment.id%>').fadeIn('slow');
$('#new_appointment')[0].reset();

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Consultorio</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.fecha %></td>
        <td><%= appointment.hora %></td>
        <td><%= appointment.consultorio %></td>
        <td><%= appointment.pet_id ? Pet.where(id: appointment.pet_id)[0].nombre : "No tiene mascotas" %></td>
        
    <% end %>
  </tbody>
</table>

<br>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @appointment.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @appointment.hora %>
</p>

<p>
  <strong>Consultorio:</strong>
  <%= @appointment.consultorio %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet_id %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>