config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins, controllers: { sessions: 'admins/sessions' } 
  devise_for :usuarios, controllers: { sessions: 'usuarios/sessions' }
  
  resources :pets do
  resources :appointments
 end
 root to: 'pets#index'

 devise_scope :admin do
	get 'admins/users/list', to: 'admins/sessions#list', as: 'users_list'
end

 get'/citas', to: 'appointments#index', as: 'appointments'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Pets" %></title>


<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<link href="assets/stylesheets/application.css" type="text/css" rel="stylesheet" media="screen,projection"/>


<nav class="indigo">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo center">Pets</a>

      <ul class="left hide-on-med-and-down">
      <% if admin_signed_in? || usuario_signed_in?%>
      <% if current_usuario.rol == 'usuario' %> 
         <li><%= link_to 'MIS MASCOTAS', pets_path, class: 'button primary' %></li>
         <li><%= link_to 'REGISTRAR MASCOTA', new_pet_path, class: 'button primary' %></li>
       <% elsif current_usuario.rol == 'veterinario'%> 
         <li><%= link_to 'VER MASCOTAS', pets_path, class: 'button primary' %></li>
         <li><%= link_to 'CITAS', '/citas', class: 'button primary' %></li>
         <% else %>
         <li><%= link_to 'USUARIOS', users_list_path, class: 'button primary' %></li>
         <li><%= link_to 'CITAS', '/citas', class: 'button primary' %></li>
         <% end %>
         <% end %>
      </ul>

      <ul class="right hide-on-med-and-down">
        <% if admin_signed_in? %> 
    <li> Bienvenido(a) <%= current_admin.email %></li>
    <li><%= link_to 'Editar perfil', edit_admin_registration_path, class: 'button primary' %></li>
    <li><%= link_to 'Cerrar Sesion', destroy_admin_session_path, method: :delete, class: 'button primary' %></li>
    
    <% elsif usuario_signed_in? %>
    <li> Bienvenido(a) <%= current_usuario.email %></li>
    <li><%= link_to 'Editar perfil', edit_usuario_registration_path, class: 'button primary' %></li>
    <li><%= link_to 'Cerrar Sesion', destroy_usuario_session_path, method: :delete, class: 'button primary' %></li>
    <% else %>
      <li><%= link_to 'Entrar',  new_usuario_session_path, class: 'button primary' %></li>
      <li><%= link_to 'Registrarse',  new_usuario_registration_path, class: 'button primary' %></li>
    <% end %>
      </ul>
      
    </div>
  
  </nav>
   
<br>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class='alert alert-<%=key%>'><%= value %></div>
      <% end %>
    </div>



    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>